graphs = {
    "skos": {
        "num_node": 144,
        "num_edge": 252,
        "labels": set(
            [
                "type",
                "label",
                "definition",
                "isDefinedBy",
                "subPropertyOf",
                "comment",
                "scopeNote",
                "inverseOf",
                "range",
                "domain",
                "contributor",
                "disjointWith",
                "creator",
                "example",
                "first",
                "rest",
                "seeAlso",
                "title",
                "description",
                "unionOf",
                "subClassOf",
            ]
        ),
    },
    "generations": {
        "num_node": 129,
        "num_edge": 273,
        "labels": set(
            [
                "type",
                "rest",
                "first",
                "onProperty",
                "intersectionOf",
                "equivalentClass",
                "someValuesFrom",
                "hasValue",
                "hasSex",
                "inverseOf",
                "sameAs",
                "hasParent",
                "hasChild",
                "range",
                "hasSibling",
                "versionInfo",
                "oneOf",
            ]
        ),
    },
    "foaf": {
        "num_node": 256,
        "num_edge": 631,
        "labels": set(
            [
                "type",
                "label",
                "term_status",
                "comment",
                "isDefinedBy",
                "domain",
                "range",
                "subPropertyOf",
                "subClassOf",
                "disjointWith",
                "inverseOf",
                "equivalentClass",
                "title",
                "description",
                "equivalentProperty",
            ]
        ),
    },
    "pr": {
        "num_node": 815,
        "num_edge": 692,
        "labels": set(["d", "a"]),
    },
    "gzip": {
        "num_node": 2687,
        "num_edge": 2293,
        "labels": set(["d", "a"]),
    },
}
