#------------------------------------------------
# GitHub Action Run Tests
#
# Copyleft (c) by Egor Ovchinnikov 2023.
#
# -----------------------------------------------

name: My-Run-Tests

on: [push]

env:
  PYTHON_VERSION: "3.10.6"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy directory from git
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: $PYTHON_VERSION
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        
